### ISSUE TITLE
Color management in PD: master tracking issue

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#103]
As of 3582b74f7df8efb31af87c0d5ba758e3209b5f4a, color management is fully implemented save for a few outlying issues and potential features.  To make this issue easier to follow, I have removed all completed tasks and pasted them into the first comment box.

Remaining non-critical tasks and/or features include: 
- [x] If a custom screen profile has been selected, cache it for performance reasons.  (Right now the profile is retrieved from disk on every screen render!)
- [ ] The Batch wizard will be getting a new Metadata panel in 6.2.  Batch-related ICC profile considerations should be handled there; I will leave details to a dedicated batch wizard issue to be created when I get to that task.
- [ ] Feature: consider an "apply custom ICC profile" option in the Image -> Metadata menu.  This would allow the user to apply any arbitrary profile to an image, almost like an adjustment or filter.
- [ ] Feature: consider an "attach custom ICC profile" option in the Image -> Metadata menu, or perhaps in a future Export menu??  The option would allow the user to attach a desired ICC profile to an image.
