### ISSUE TITLE
6.4 Roadmap (expected release date: first week or two of September)

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#122]
**Updated 26 August 2014**

**New features available in 6.4**

Layer overhaul:
- [x] Convert back-end to operate on multi-layer pdImage objects
- [x] Implement dedicated layer toolbox
- [x] Implement dedicated layer menu
- [x] Implement creating new layers from existing files
- [x] Get Edit menu working with layers
- [x] Get Image menu working with layers
- [x] Get Selection menu (and selection tools) working with layers
- [x] Implement custom blend modes _(thank you to @audioglider for his help with this)_
- [x] New PDI file format for saving layered images and all relevant image data 
- [x] Add metadata support to PDI files

Undo/Redo overhaul:
- [x] Move to an active Undo/Redo engine _(vs the old passive method)_
- [x] Rewrite engine as diff-based, rather than "always save whole image stack"
- [x] Support individual diffs for five categories: full image stack, image header only, full layer data, layer header only, selection data
- [x] Add support for "Undo to arbitrary position" 
- [x] Rewrite Autosave engine to integrate with new Undo/Redo data format
- [x] New Undo History browser, with full support for thumbnails of all Undo types (including selections)
- [x] Improve Edit > Fade tool, which is basically part of the Undo engine (as it relies on pdUndo to retrieve past image states from file.
- [x] Support for variable Undo/Redo compression, via Tools > Options

Input overhaul:
- [x] New PD-specific input backend _(now available via the pdInput class)_
- [x] Improved support for arrow keys on tools _(as of 13 June, all tools now support arrow key interactions)_
- [x] Improved support for any other expected keyboard modifiers

UI improvements:
- [x] Replace scroll bars with PD-specific custom slider
- [x] Implement custom slider styles, to help convey specific tool purposes
- [x] Replace radio buttons with PD-specific (and Unicode-compatible) custom version
- [x] Replace check boxes with PD-specific (and Unicode-compatible) custom version

**New tools available in 6.4**

On-canvas tools:
- [x] Dedicated Move/Resize tool for moving and resizing layers
- [x] Non-destructive layer resizing via Move/Resize tool
- [x] Quick-fix tools for applying basic, non-destructive corrections without having to go to the menu.
- [x] Improve mousewheel zoom, so that zooming to a cursor location maintains the position of that pixel on the screen.

Edit menu tools:
- [x] Edit -> Cut
- [x] Edit -> Cut from layer (default Cut operation in other photo editors; see 24967b6cb12174b7acc9bb488482c639bacf8eaa for why PD uses the order it does)
- [x] Edit -> Clear _(ended up going with Select -> Erase selected area instead)_

Image menu tools:
- [x] Image -> Straighten (and corresponding Layer -> Straighten)
- [x] Image -> Fit Canvas to Active Layer
- [x] Image -> Fit Canvas around All Layers
- [x] Image -> Trim Empty Borders

Adjustment menu tools:
- [x] Adjustments -> Auto correct -> Color, Contrast, and Lighting
- [x] Adjustments -> Auto enhance -> Color, Contrast, and Lighting
- [x] Adjustments -> Photography -> HDR _(imitation only at present, e.g. exposure stack not required)_
- [x] Adjustments -> Photography -> Split Toning _(courtesy of @audioglider)_

Effect menu tools:
_(Many thanks to @audioglider, who is responsible for many of these!)_
- [x] Effects -> Artistic -> Glass Tiles _(courtesy of @audioglider)_
- [x] Effects -> Artistic -> Stained Glass
- [x] As part of the Stained Glass filter, above, PD now has a working Voronoi backend via pdVoronoi (http://en.wikipedia.org/wiki/Voronoi)
- [x] Effects -> Blur -> Fragment _(courtesy of @audioglider)_
- [x] Effects -> Blur -> Kuwahara filter _(courtesy of @audioglider)_
- [x] Effects -> Lighting -> Lens flare _(courtesy of @audioglider)_
- [x] Effects -> Lighting -> Sunshine _(courtesy of @audioglider)_
- [x] Effects -> Noise -> Remove noise (Bilateral filter) _(courtesy of @audioglider)_

**Existing tool updates available in 6.4**

Image Menu:
- [x] Improve Content-aware Resize tool (seam removal is now directionally symmetrical; tool memory usage reduced by as much as 50%; better accuracy of energy map function; improved 32bpp handling; add ESC-to-cancel functionality)
- [x] Convert 90/180/270 rotations to GDI+

Adjustments Menu:
- [x] Add Shadow/Midtone/Highlight support to Adjustments -> Color balance _(courtesy of @audioglider)_
- [x] Revamp Levels dialog to a more industry-standard layout, with histogram view
- [x] Curve tool update to support individual RGB curves

Effects Menu:
- [x] Overhaul Effects -> Artistic -> Comic book tool
- [x] Overhaul Effects -> Artistic -> Relief tool
- [x] Overhaul Effects -> Artistic -> Pencil Drawing tool (now called "Colored pencil")
- [x] Overhaul Effects -> Edge -> Emboss tool to support variable angle, depth, and stroke size
- [x] Overhaul Effects -> Edge -> Enhance Edges tool to support all edge detection algorithms, variable directionality, and variable strength
- [x] Update Effects -> Edge -> Find edges tool to support directionality, including bidirectional support for Prewitt, Sobel, etc
- [x] Overhaul Nature -> Fire effect (now called "Ignite") with full dialog and configurable options
- [x] Overhaul Nature -> Fog effect with full dialog and configurable options
- [x] Overhaul Nature -> Rainbow effect (now found in the "Light and Shadow" category) with full dialog and configurable options

**Other notable changes in 6.4**
- [x] Improved drag/drop and copy/paste from web browsers _(Still some issues with linked images, as some browsers will only report the target URL instead of the image link - will investigate)_
- [x] Replaced abandoned pngnq-s9 plugin with the official pngquant library.
- [x] Performance Preferences section now available, enabling faster tools at a quality trade-off.  _(Note that quality only affects the on-screen viewport, not the quality of image operations themselves)_.
- [x] Custom debugger added to nightly builds, with built-in support for memory leak checks
- [x] Custom performance profiler added to nightly builds, with built-in support for tracking across multiple runs
- [x] Improve start-up performance

**Improvements and bug-fixes added between Beta 1 and Beta 2**
- [x] Fix various flickering issues across the UI
- [x] Fix critical crashes in tools that use PD's central compositor (pre-multiplied alpha issue)
- [x] Further improvements to 24 > 32bpp conversion code
- [x] Fix alignment issues when toggling floating vs docked toolbars
- [x] Improve top-most behavior of child dialogs while in docked toolbar mode
- [x] Various bug-fixes to new radio button and check box UCs
- [x] Added failsafe catches for various processor calls deprecated from 6.2 (to prevent crashes when running old macros)
- [x] New preference for disabling EXIF auto-rotate (to fix issues where Windows Photo Viewer writes broken Orientation tags)
- [x] Large performance improvements to Translation engine
- [x] Fixed broken drag/drop images coming from IE
- [x] Batch wizard: fix potential crash during image previewing
- [x] Recent Files: fix serious crash when recent files go missing mid-session
- [x] UI: various layout changes to better support long translations
