### ISSUE TITLE
PhotoDemon 6.6 beta checklist

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#150]
I had originally planned for the 6.6 release to include a full complement of paint tools, as well as full Unicode support, but I'm now inclined to spread out those features across several point releases.  There are a number of reasons for this, but most significantly, I've fixed a number of severe bugs across wide portions of the program, and many of the fixes are so deeply embedded that backporting them into 6.4's codebase would be a nightmare.  

I also think that the massive size of 6.4's release makes a smaller 6.6 release more palatable.  There are still a lot of neat new features - expanded selection tools in particular - and it might be nice to have some testing on all the new user controls that have been implemented.  Also, work on PD tends to slow as we enter the holiday season, so it's a good time for me to tackle some smaller issues, instead of huge, messy projects like ongoing Unicode user control work.

So this meta-issue is to track blockers for a 6.6 beta release.  Ideally, I would like to have the beta released before December is out, with a formal 6.6 release happening some time in January.  

Issues are in no particular order.

- [x] Update splash screen and other assets to 6.6.  *(Still undecided on what to do with the About dialog, but that's low priority relative to other release issues.)*
- [x] Clean up main interface and remove warning
- [x] Write new linear conversion code for high-bit-depth images (see #149)
- [x] ~~See if I can salvage custom Win 7 code, even when DEP is enabled (see 033cb908fb8c7389206e31b854d7b0c6bb4bbcb5)~~ *(Not feasible at present; might investigate later, pending discussion with vbForums users who are currently investigating their own workarounds.)*
- [x] Language translations; see #156 for detailed tracking of this issue
- [x] Automatic update patching.  Work is currently underway using the great update features developed for language updates.  Hope to have this ready within a week or two.

**Comment by tannerhelland** [comment]
I thought I was just about ready to release a 6.6 beta, but automatic updates need a bit more work.  

I hoped to just use a .batch file for restarting the program, but this has proven to have unpredictable issues, particularly on older PCs where PD takes a long time to shut down, so the batch script fires too early.  There are ways to force a batch file delay, but they don't work on all Windows versions, so rather than keep fighting this, I'm just going to write a small patch program that waits for PD to close, verifies that the update was successful, then restarts (or restores the old version) as necessary.

**Comment by tannerhelland** [comment]
After three successful betas, I think PD 6.6 is just about ready for release.  Any remaining issues (barring major bugs that appear in the next day or two) will be postponed until 6.8.
